services:
  mysql:
    image: mysql:8.0
    container_name: mysql_apm
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apm_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro

volumes:
  mysql-data:
